(lang dune 3.22)

(name EncloseCamel)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Ben Han, Maxwell Li, Daniel Lee, Caleb Helsel, Jiayi Bai")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name EncloseCamel)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
